version: '3.8'

services:
  db:
    image: mysql:latest
    container_name: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: testdb
    volumes:
      - db_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: my-admin
    ports:
      - "8080:80"
    environment:
      PMA_HOST: db
      PMA_PORT: 3306

volumes:
  db_data:
